<?php
/**
 * This file is part of the ATK distribution on GitHub.
 * Detailed copyright and licensing information can be found
 * in the doc/COPYRIGHT and doc/LICENSE files which should be
 * included in the distribution.
 *
 * @package atk
 *
 * This file contains variables about this ATK version and the
 * state of the code such as development or stable.
 *
 * @copyright (c)2000-2010 Ibuildings.nl BV
 * @license http://www.achievo.org/atk/licensing ATK Open Source License
 *
 * @version $Revision$
 * $Id$
 */
/**
 * The current atk version
 */
//$atk_version = "6.6"; // iBuildings  https://github.com/ibuildingsnl/ATK
//$atk_version = "7.0"; // Community https://github.com/atkphpframework/atk-community
//$atk_version = "8.2.7"; // Sintattica https://github.com/Sintattica/atk
//$atk_version = "8.2.8"; // BadPenguin https://github.com/badpenguin/atk-8
$atk_version = "8.5.0"; // WayneH https://github.com/wayneh/atk-85 
return $atk_version; 
